load("//tools/verilator:rules.bzl", "cc_sv_library_verilator")

cc_sv_library_verilator(
    name = "KW_ror_static_cc",
    srcs = ["KW_ror_static_wrap.sv"],
    top = "KW_ror_static_wrap",
    deps = ["//grip/rtl/lib/comb:KW_ror_static"],
)

cc_sv_library_verilator(
    name = "KW_rol_static_cc",
    srcs = ["KW_rol_static_wrap.sv"],
    top = "KW_rol_static_wrap",
    deps = ["//grip/rtl/lib/comb:KW_rol_static"],
)

cc_sv_library_verilator(
    name = "KW_decode_cc",
    srcs = ["KW_decode_wrap.sv"],
    top = "KW_decode_wrap",
    deps = ["//grip/rtl/lib/comb:KW_decode"],
)

cc_sv_library_verilator(
    name = "KW_decode_v_cc",
    srcs = ["KW_decode_v_wrap.sv"],
    top = "KW_decode_v_wrap",
    deps = ["//grip/rtl/lib/comb:KW_decode_v"],
)

cc_sv_library_verilator(
    name = "KW_priority_encoder_cc",
    srcs = ["KW_priority_encoder_wrap.sv"],
    top = "KW_priority_encoder_wrap",
    deps = ["//grip/rtl/lib/comb:KW_priority_encoder"],
)

cc_sv_library_verilator(
    name = "KW_mux_n_onehot_cc",
    srcs = ["KW_mux_n_onehot_wrap.sv"],
    top = "KW_mux_n_onehot_wrap",
    deps = ["//grip/rtl/lib/comb:KW_mux_n_onehot"],
)

cc_sv_library_verilator(
    name = "KW_transpose_packed_2d_cc",
    srcs = ["KW_transpose_packed_2d_wrap.sv"],
    top = "KW_transpose_packed_2d_wrap",
    deps = ["//grip/rtl/lib/comb:KW_transpose_packed_2d"],
)

cc_sv_library_verilator(
    name = "KW_bit_reverse_cc",
    srcs = ["KW_bit_reverse_wrap.sv"],
    top = "KW_bit_reverse_wrap",
    deps = ["//grip/rtl/lib/comb:KW_bit_reverse"],
)
