load("//tools:verilog.bzl", "sv_library")

sv_library(
    name = "KW_clock_div",
    srcs = ["KW_clock_div.sv"],
    visibility = ["//grip/rtl:__subpackages__"],
)

sv_library(
    name = "KW_reset_sync",
    srcs = ["KW_reset_sync.sv"],
    visibility = ["//grip/rtl:__subpackages__"],
)
